INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Luiz Henrique', 'Castro', 46, 'luizhenrique.castro@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Maria Eduarda', 'Jesus', 36, 'mariaeduarda.jesus@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Joaquim', 'Cardoso', 62, 'joaquim.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Luiz Otávio', 'da Mata', 53, 'luizotávio.damata@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Lorena', 'Dias', 72, 'lorena.dias@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Davi Lucas', 'Campos', 62, 'davilucas.campos@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Gabriela', 'Azevedo', 39, 'gabriela.azevedo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Vinicius', 'Rocha', 45, 'vinicius.rocha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Gabriel', 'Azevedo', 26, 'gabriel.azevedo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('João Guilherme', 'Lopes', 38, 'joãoguilherme.lopes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Juliana', 'Rezende', 24, 'juliana.rezende@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Laura', 'Cardoso', 75, 'analaura.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Juliana', 'da Paz', 52, 'juliana.dapaz@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Luiz Henrique', 'Mendes', 40, 'luizhenrique.mendes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Sarah', 'Moreira', 53, 'sarah.moreira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bruno', 'Silva', 61, 'bruno.silva@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Thales', 'Martins', 75, 'thales.martins@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Davi Lucas', 'Barbosa', 31, 'davilucas.barbosa@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Vitor Hugo', 'Santos', 67, 'vitorhugo.santos@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Lara', 'Melo', 18, 'lara.melo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Julia', 'Castro', 21, 'anajulia.castro@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Marcela', 'Teixeira', 37, 'marcela.teixeira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Pietra', 'Nunes', 33, 'pietra.nunes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Kevin', 'Caldeira', 42, 'kevin.caldeira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('João Gabriel', 'Ramos', 53, 'joãogabriel.ramos@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Vitor Hugo', 'Carvalho', 19, 'vitorhugo.carvalho@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Diego', 'Peixoto', 77, 'diego.peixoto@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('João Lucas', 'Correia', 27, 'joãolucas.correia@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Sarah', 'Cardoso', 25, 'sarah.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Davi', 'Jesus', 49, 'davi.jesus@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Camila', 'Almeida', 24, 'camila.almeida@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Cauã', 'Gonçalves', 65, 'cauã.gonçalves@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Júlia', 'Viana', 80, 'anajúlia.viana@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Caio', 'Cardoso', 27, 'caio.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('João Felipe', 'Cardoso', 67, 'joãofelipe.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Gustavo Henrique', 'Silva', 63, 'gustavohenrique.silva@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Clara', 'Carvalho', 40, 'clara.carvalho@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Júlia', 'Cavalcanti', 72, 'júlia.cavalcanti@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Otávio', 'Araújo', 41, 'otávio.araújo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Isabella', 'Moura', 58, 'isabella.moura@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Gabriel', 'Ferreira', 33, 'gabriel.ferreira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Melissa', 'Cunha', 43, 'melissa.cunha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Lorenzo', 'Caldeira', 21, 'lorenzo.caldeira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Elisa', 'Almeida', 54, 'elisa.almeida@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Cauê', 'Monteiro', 46, 'cauê.monteiro@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Davi Lucca', 'Cavalcanti', 59, 'davilucca.cavalcanti@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Kaique', 'Almeida', 48, 'kaique.almeida@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Calebe', 'Silva', 23, 'calebe.silva@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Gustavo Henrique', 'Porto', 21, 'gustavohenrique.porto@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Isabella', 'Costela', 60, 'isabella.costela@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bryan', 'Silva', 44, 'bryan.silva@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Kevin', 'Novaes', 19, 'kevin.novaes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Pietro', 'Campos', 64, 'pietro.campos@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Antônio', 'Silveira', 27, 'antônio.silveira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Raul', 'Castro', 20, 'raul.castro@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Maysa', 'Melo', 38, 'maysa.melo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Sofia', 'Cunha', 79, 'sofia.cunha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('João Vitor', 'Caldeira', 68, 'joãovitor.caldeira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Laís', 'Azevedo', 63, 'laís.azevedo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Rodrigo', 'Sales', 79, 'rodrigo.sales@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Laura', 'Cardoso', 26, 'ana.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bruna', 'Sales', 62, 'bruna.sales@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Renan', 'Carvalho', 32, 'renan.carvalho@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Yasmin', 'Almeida', 21, 'yasmin.almeida@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Thiago', 'Rocha', 73, 'thiago.rocha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('João Felipe', 'Jesus', 61, 'joãofelipe.jesus@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Laís', 'Santos', 47, 'laís.santos@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Pedro', 'Freitas', 33, 'pedro.freitas@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Alice', 'Nogueira', 70, 'alice.nogueira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Thiago', 'Gomes', 69, 'thiago.gomes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Otávio', 'Souza', 52, 'otávio.souza@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Sophia', 'Freitas', 72, 'anasophia.freitas@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Esther', 'Nunes', 37, 'esther.nunes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bruna', 'Azevedo', 72, 'bruna.azevedo@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bernardo', 'Moura', 41, 'bernardo.moura@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Emanuel', 'Farias', 46, 'emanuel.farias@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Julia', 'Costa', 63, 'anajulia.costa@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bárbara', 'Fernandes', 42, 'bárbara.fernandes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Lívia', 'Fogaça', 74, 'analívia.fogaça@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Vicente', 'Cardoso', 60, 'vicente.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Isis', 'Peixoto', 49, 'isis.peixoto@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Larissa', 'Cardoso', 50, 'larissa.cardoso@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Igor', 'Porto', 75, 'igor.porto@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Fernanda', 'Campos', 48, 'fernanda.campos@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Clara', 'da Costa', 56, 'anaclara.dacosta@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Isabella', 'Cunha', 53, 'isabella.cunha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Vitória', 'Sales', 21, 'anavitória.sales@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Alana', 'Mendes', 28, 'alana.mendes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Giovanna', 'Costa', 71, 'giovanna.costa@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Luigi', 'Caldeira', 24, 'luigi.caldeira@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Beatriz', 'Pires', 29, 'beatriz.pires@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Breno', 'Farias', 66, 'breno.farias@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Vitória', 'Rocha', 31, 'vitória.rocha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Bárbara', 'da Rocha', 54, 'bárbara.darocha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Murilo', 'Mendes', 41, 'murilo.mendes@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Luiz Henrique', 'Rezende', 80, 'luizhenrique.rezende@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Ana Carolina', 'Freitas', 42, 'anacarolina.freitas@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Larissa', 'da Cunha', 31, 'larissa.dacunha@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Milena', 'Jesus', 58, 'milena.jesus@sicooperative.com.br');
INSERT INTO sicooperative.associado (nome_associado, sobrenome_associado, idade_associado, email_associado) VALUES ('Nicole', 'Lopes', 35, 'nicole.lopes@sicooperative.com.br');